=== hypoport/axilaris-engine-api/src/main/resources/schema/axilarisErmittlungsRequest.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "axilaris-engine-api Ermittlungsrequest",
  "id": "http://jsonschema.net/axilaris-engine-api/ermittlung/request",
  "type": "object",
  "properties": {
    "metadaten": {
      "$ref": "axilarisRequest.json#/metadaten"
    },
    "kreditwunsch": {
      "$ref": "axilarisRequest.json#/kreditwunsch"
    },
    "antragsteller": {
      "$ref": "axilarisRequest.json#/antragsteller"
    },
    "gemeinsameAntragstellerAngaben": {
      "$ref": "axilarisRequest.json#/gemeinsameAntragstellerAngaben"
    },
    "konto": {
      "$ref": "axilarisDefinitions.json#/konto"
    },
    "abzuloesendeVerbindlichkeiten": {
      "$ref": "axilarisRequest.json#/abzuloesendeVerbindlichkeiten"
    },
    "finanzierungsZweck": {
      "$ref": "axilarisRequest.json#/finanzierungsZweck"
    },
    "fahrzeugDaten": {
      "$ref": "axilarisRequest.json#/fahrzeugDaten"
    },
    "kundenBetreuer": {
      "$ref": "axilarisRequest.json#/kundenBetreuer"
    },
    "handelsbeziehungen": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "produktAnbieterId": {
            "type": "string"
          },
          "vertriebsGruppe": {
            "type": "string"
          },
          "kreditProvisionsWunsch": {
            "$ref": "axilarisDefinitions.json#/percent"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== hypoport/axilaris-engine-api/src/main/resources/schema/axilarisRequest.json
{
  "metadaten": {
    "type": "object",
    "properties": {
      "traceId": {
        "type": "boolean"
      },
      "vorgangsNummer": {
        "type": "boolean"
      }
    },
    "additionalProperties": false
  },
  "kreditwunsch": {
    "type": "object",
    "properties": {
      "auszahlungsBetrag": {
        "type": "number"
      },
      "ratenZahlungTermin": {
        "type": "integer"
      },
      "laufzeitInMonaten": {
        "type": "integer"
      },
      "rateProMonat": {
        "type": "number"
      },
      "versicherungsWunsch": {
        "type": "object",
        "properties": {
          "leben": {
            "type": "boolean"
          },
          "arbeitsUnfaehigkeit": {
            "type": "boolean"
          },
          "arbeitsLosigkeit": {
            "type": "boolean"
          },
          "kreditNehmerId": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "additionalProperties": false
  },
  "antragsteller": {
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "haushaltsPartnerId": {
          "type": "string"
        },
        "persoenlicheAngaben": {
          "type": "object",
          "properties": {
            "anrede": {
              "$ref": "definitions.json#/anrede"
            },
            "titel": {
              "type": "string"
            },
            "vorname": {
              "type": "string"
            },
            "nachname": {
              "type": "string"
            },
            "geburtsDatum": {
              "type": "string",
              "format": "date-time"
            },
            "geburtsOrt": {
              "type": "string"
            },
            "geburtsName": {
              "type": "string"
            },
            "staatsAngehoerigkeit": {
              "type": "string"
            },
            "familienStand": {
              "type": "string"
            },
            "anzahlPersonenImHaushalt": {
              "type": "integer"
            }
          },
          "additionalProperties": false
        },
        "angabenZurBeschaeftigung": {
          "type": "object",
          "properties": {
            "beschaeftigungsVerhaeltnis": {
              "enum": [
                "ANGESTELLT",
                "ARBEITER",
                "BEAMTER",
                "GF_GESELLSCHAFTER",
                "SELBSTAENDIG",
                "FREIBERUFLER",
                "RENTNER",
                "HAUSFRAU",
                "ARBEITSLOS"
              ]
            },
            "befristet": {
              "enum": [
                "UNLIMITED",
                "LIMITED",
                "PROBATIONARY"
              ]
            },
            "beschaeftigtSeit": {
              "type": "string",
              "format": "date-time"
            },
            "befristetBis": {
              "type": "string",
              "format": "date-time"
            },
            "beruf": {
              "type": "string"
            },
            "branche": {
              "enum": [
                "HOUSING_INDUSTRIES",
                "SERVICES",
                "ENERGY_SUPPLIER",
                "LOCAL_AUTHORITY",
                "RETAIL",
                "GASTRONOMIE",
                "FINANCING",
                "AGRICULTURE",
                "PUBLIC_SERVICE",
                "NON_PROFIT",
                "PRIVATE_HOMES",
                "SOCIAL_SECURITY",
                "MANUFACTURING",
                "TELECOMMUNICATION",
                "OTHERS"
              ]
            },
            "anschrift": {
              "$ref": "definitions.json#/adresse"
            },
            "nameArbeitgeber": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "angabenZurVorherigenBeschaeftigung": {
          "type": "object",
          "properties": {
            "beschaeftigtSeit": {
              "type": "string",
              "format": "date-time"
            },
            "befristetBis": {
              "type": "string",
              "format": "date-time"
            },
            "anschrift": {
              "$ref": "definitions.json#/adresse"
            },
            "nameArbeitgeber": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "wohnsituation": {
          "type": "object",
          "properties": {
            "wohnArt": {
              "enum": [
                "BY_RENT",
                "OWN_RESIDENCE",
                "AT_PARENTS",
                "BY_SUBLETTING"
              ]
            },
            "wohnhaftSeit": {
              "type": "string",
              "format": "date-time"
            },
            "anschrift": {
              "$ref": "definitions.json#/adresse"
            },
            "vorAnschrift": {
              "$ref": "definitions.json#/adresse"
            },
            "wohnhaftSeitVorAnschrift": {
              "type": "string",
              "format": "date-time"
            },
            "anzahlPkw": {
              "type": "integer"
            }
          },
          "additionalProperties": false
        },
        "kontakt": {
          "type": "object",
          "properties": {
            "telefonPrivat": {
              "type": "string"
            },
            "telefonGeschaeftlich": {
              "type": "string"
            },
            "eMail": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "herkunft": {
          "type": "object",
          "properties": {
            "aufenthaltstitel": {
              "type": "object",
              "properties": {
                "inDeutschlandSeit": {
                  "type": "string",
                  "format": "date-time"
                },
                "art": {
                  "enum": [
                    "PERMISSION_UNLIMITED",
                    "PERMISSION_LIMITED",
                    "ALLOWANCE"
                  ]
                },
                "befristetBis": {
                  "type": "string",
                  "format": "date-time"
                }
              },
              "additionalProperties": false
            },
            "arbeitsErlaubnisBefristetBis": {
              "type": "string",
              "format": "date-time"
            }
          },
          "additionalProperties": false
        },
        "ausgaben": {
          "$ref": "definitions.json#/ausgaben"
        },
        "einnahmen": {
          "$ref": "definitions.json#/einnahmen"
        },
        "vermoegen": {
          "$ref": "definitions.json#/vermoegen"
        },
        "verbindlichkeiten": {
          "$ref": "definitions.json#/verbindlichkeiten"
        },
        "anzahlKinder": {
          "type": "integer"
        },
        "rentenVersicherung": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "anschrift": {
              "$ref": "definitions.json#/adresse"
            },
            "rentnerSeit": {
              "type": "string",
              "format": "date-time"
            }
          },
          "additionalProperties": false
        },
        "legitimation": {
          "type": "object",
          "properties": {
            "ausweisArt": {
              "enum": [
                "PERSONALAUSWEIS",
                "REISEPASS",
                "ANDERER_AUSWEIS"
              ]
            },
            "ausweisNummer": {
              "type": "string"
            },
            "ausstellendeBehoerde": {
              "type": "string"
            },
            "ausstellungsDatum": {
              "type": "string",
              "format": "date-time"
            },
            "ausstellungsOrt": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "additionalProperties": false
  },
  "gemeinsameAntragstellerAngaben": {
    "type": "object",
    "properties": {
      "ausgaben": {
        "$ref": "definitions.json#/ausgaben"
      },
      "einnahmen": {
        "$ref": "definitions.json#/einnahmen"
      },
      "vermoegen": {
        "$ref": "definitions.json#/vermoegen"
      },
      "verbindlichkeiten": {
        "$ref": "definitions.json#/verbindlichkeiten"
      },
      "anzahlKinder": {
        "type": "integer"
      }
    },
    "additionalProperties": false
  },
  "abzuloesendeVerbindlichkeiten": {
    "type": "object",
    "properties": {
      "ratenkredite": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "monatlicheRate": {
              "type": "number"
            },
            "letzteRate": {
              "type": "number"
            },
            "datumErsteRate": {
              "type": "string",
              "format": "date-time"
            },
            "datumLetzteRate": {
              "type": "string",
              "format": "date-time"
            },
            "urspruenglicherBetrag": {
              "type": "number"
            },
            "abloeseBetrag": {
              "type": "number"
            },
            "konto": {
              "$ref": "definitions.json#/konto"
            }
          },
          "additionalProperties": false
        }
      },
      "sonstigeVerbindlichkeiten": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "monatlicheRate": {
              "type": "number"
            },
            "letzteRate": {
